// Generated by GraphWalker (http://www.graphwalker.org)
package org.mc646.tests.statemodel;

import org.graphwalker.java.annotation.Model;
import org.graphwalker.java.annotation.Vertex;
import org.graphwalker.java.annotation.Edge;

@Model(file = "org/mc646/tests/OPDModel.json")
public interface IOpdModel {

    @Vertex()
    void v_OpdEditRegistration();

    @Edge()
    void e_OpdDelete();

    @Vertex()
    void v_QuestionDelete();

    @Edge()
    void e_SaveOpd();

    @Edge()
    void e_SearchAllFields();

    @Edge()
    void e_DeleteYes();

    @Edge()
    void e_SearchOneWeek();

    @Edge()
    void e_OpdEdit();

    @Vertex()
    void v_Opd();

    @Edge()
    void e_Cancel();

    @Edge()
    void e_DeleteNo();

    @Edge()
    void e_ValidData();

    @Edge()
    void e_InvalidData();

    @Edge()
    void e_SearchPatientID();

    @Edge()
    void e_OpdNew();

    @Vertex()
    void v_OpdRegistration();

    @Edge()
    void e_NewEdge();
}
